# -*- coding: utf-8 -*-

import os

from django.conf import settings

from icebergsdk.conf import Configuration, ConfigurationStage, ConfigurationDebug, ConfigurationSandbox, ConfigurationSandboxStage, ConfigurationDebugSandbox


class ConfigurationProd(Configuration):
    ICEBERG_API_PRIVATE_KEY = getattr(settings, 'ICEBERG_API_PRIVATE_KEY', os.getenv('ICEBERG_API_PRIVATE_KEY', None))
    ICEBERG_APPLICATION_NAMESPACE = getattr(settings, 'ICEBERG_APPLICATION_NAMESPACE', os.getenv('ICEBERG_APPLICATION_NAMESPACE', None))
    ICEBERG_APPLICATION_SECRET_KEY = getattr(settings, 'ICEBERG_APPLICATION_SECRET_KEY', os.getenv('ICEBERG_APPLICATION_SECRET_KEY', None))


class ConfigurationSandbox(ConfigurationSandbox):
    ICEBERG_API_PRIVATE_KEY = getattr(settings, 'ICEBERG_API_PRIVATE_KEY_SANDBOX', os.getenv('ICEBERG_API_PRIVATE_KEY_SANDBOX', None))
    ICEBERG_APPLICATION_NAMESPACE = getattr(settings, 'ICEBERG_APPLICATION_NAMESPACE_SANDBOX', os.getenv('ICEBERG_APPLICATION_NAMESPACE_SANDBOX', None))
    ICEBERG_APPLICATION_SECRET_KEY = getattr(settings, 'ICEBERG_APPLICATION_SECRET_KEY_SANDBOX', os.getenv('ICEBERG_APPLICATION_SECRET_KEY_SANDBOX', None))


class ConfigurationSandboxStage(ConfigurationSandboxStage):
    ICEBERG_API_PRIVATE_KEY = getattr(settings, 'ICEBERG_API_PRIVATE_KEY_SANDBOX_STAGE', os.getenv('ICEBERG_API_PRIVATE_KEY_SANDBOX_STAGE', None))
    ICEBERG_APPLICATION_NAMESPACE = getattr(settings, 'ICEBERG_APPLICATION_NAMESPACE_SANDBOX_STAGE', os.getenv('ICEBERG_APPLICATION_NAMESPACE_SANDBOX_STAGE', None))
    ICEBERG_APPLICATION_SECRET_KEY = getattr(settings, 'ICEBERG_APPLICATION_SECRET_KEY_SANDBOX_STAGE', os.getenv('ICEBERG_APPLICATION_SECRET_KEY_SANDBOX_STAGE', None))

class ConfigurationStage(ConfigurationStage):
    ICEBERG_API_PRIVATE_KEY = getattr(settings, 'ICEBERG_API_PRIVATE_KEY_STAGE', os.getenv('ICEBERG_API_PRIVATE_KEY_STAGE', None))
    ICEBERG_APPLICATION_NAMESPACE = getattr(settings, 'ICEBERG_APPLICATION_NAMESPACE_STAGE', os.getenv('ICEBERG_APPLICATION_NAMESPACE_STAGE', None))
    ICEBERG_APPLICATION_SECRET_KEY = getattr(settings, 'ICEBERG_APPLICATION_SECRET_KEY', os.getenv('ICEBERG_APPLICATION_SECRET_KEY', None))


# Debug/Local
class ConfigurationDebug(ConfigurationDebug):
    ICEBERG_API_PRIVATE_KEY = getattr(settings, 'ICEBERG_API_PRIVATE_KEY_DEBUG', os.getenv('ICEBERG_API_PRIVATE_KEY_DEBUG', None))
    ICEBERG_APPLICATION_NAMESPACE = getattr(settings, 'ICEBERG_APPLICATION_NAMESPACE_DEBUG', os.getenv('ICEBERG_APPLICATION_NAMESPACE_DEBUG', None))
    ICEBERG_APPLICATION_SECRET_KEY = getattr(settings, 'ICEBERG_APPLICATION_SECRET_KEY_DEBUG', os.getenv('ICEBERG_APPLICATION_SECRET_KEY_DEBUG', None))


class ConfigurationDebugSandbox(ConfigurationDebugSandbox):
    ICEBERG_API_PRIVATE_KEY = getattr(settings, 'ICEBERG_API_PRIVATE_KEY_DEBUG_SANDBOX', os.getenv('ICEBERG_API_PRIVATE_KEY_DEBUG_SANDBOX', None))
    ICEBERG_APPLICATION_NAMESPACE = getattr(settings, 'ICEBERG_APPLICATION_NAMESPACE_DEBUG_SANDBOX', os.getenv('ICEBERG_APPLICATION_NAMESPACE_DEBUG_SANDBOX', None))
    ICEBERG_APPLICATION_SECRET_KEY = getattr(settings, 'ICEBERG_APPLICATION_SECRET_KEY_DEBUG_SANDBOX', os.getenv('ICEBERG_APPLICATION_SECRET_KEY_DEBUG_SANDBOX', None))




